Support produce message overlap
reaktivity/nukleus-kafka.java pull request #211
Opened 2020-11-14 07:08 UTC by akrambek

2020-11-23 02:21 UTC, jfallows requested changes

2020-11-23 02:21 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/stream/KafkaCacheServerProduceFactory.java
> +                                       .partition(par -> par.partitionId(partitionId).partitionOffset(DEFAULT_LATEST_OFFSET)))
Suggest `part` instead of `par` here, or else `pr` instead of `p` for `produce(...)` lambda, leaving `p` for partition lambda.

2020-11-23 02:21 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/stream/KafkaChecksum.java
> +     * The code below comes from zlib and JCraft's CRC32C implementation
Shouldn't this say "JCraft's CRC32 implementation" (not CRC32C) since that's why we needed to change the polynomial.

2020-11-23 02:21 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/stream/KafkaClientProduceFactory.java
> +        private int dataValueCompleteSize;
I think we probably need to rename these two fields, let's discuss.

2020-11-23 02:21 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/stream/KafkaClientProduceFactory.java
> +            }
Wouldn't we want to calculate the checksum the same way whether or not `fin` flag is present?

2020-11-23 02:21 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/stream/KafkaClientProduceFactory.java
> +        private long getChecksum(
Please rename to `computeChecksum`.

2020-11-23 02:21 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/stream/KafkaMergedFactory.java
> +                                       .partition(par -> par.partitionId(partitionId).partitionOffset(
Same feedback as before on `p` vs `par` naming.

2020-11-23 02:21 UTC, jfallows commented on src/main/reaktivity/internal.idl
> +          int32 flags = 0;  // 0x01 = DIRTY 0x02 = COMPLETED
add a comma after `DIRTY` in comment for clarity

2020-11-23 23:18 UTC, akrambek reviewed
Applied feedback

2020-11-26 18:49 UTC, jfallows requested changes

2020-11-26 18:49 UTC, jfallows commented on src/main/java/org/reaktivity/nukleus/kafka/internal/cache/KafkaCachePartition.java
> +    public static final int CACHE_ENTRY_FLAGS_COMPLETED = 0x02;
`private`?

2020-11-26 18:51 UTC, akrambek commented on src/main/java/org/reaktivity/nukleus/kafka/internal/cache/KafkaCachePartition.java
> +    public static final int CACHE_ENTRY_FLAGS_COMPLETED = 0x02;
yep

2020-11-26 22:56 UTC, jfallows approved these changes

2020-11-26 23:00 UTC, merged